# Generated by Django 3.2.9 on 2022-02-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20220218_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='emotion',
            field=models.CharField(default='nope', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='emotion',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
